/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:eefce39f-be38-4d2b-9061-669b5b46a236",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_H82Z62k4v",
    "aws_user_pools_web_client_id": "3d3q87fkfn56e3d7ucc2vkfke0",
    "oauth": {}
};


export default awsmobile;
